language: python
python:
  - "3.5"
  - "3.6"
services: postgresql
addons:
  postgresql: "9.5"
install:
  - pip install .
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database frbcat;' -U postgres
  - psql -U postgres frbcat < db/create_db_tables.sql
  - psql -U postgres frbcat < tests/fill_db_test_data.sql
script:
  - py.test --cov=pyfrbcatdb --cov-report term --cov-report xml:cov.sml tests/
after_success:
  - bash <(curl -s https://codecov.io/bash)
